name: Activate OVH GPU Machine
on:
  workflow_dispatch:

jobs:
  curl:
    name: "Call to OVH"
    runs-on: ubuntu-latest
    steps:
      - name: "Call API"
        id: api
        run: |
          curl -X POST https://carnets.fabrique.social.gouv.fr/api/healthz
      - name: "Get response"
        run: echo ${{ steps.api.outputs.response }}
